import { Product, Review } from '@/types';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Professional Camera',
    slug: 'professional-camera',
    description: 'High-quality professional DSLR camera with 24MP sensor and 4K video recording capabilities. Perfect for photography enthusiasts and professionals.',
    price: 1299.99,
    brand: 'TechCam',
    category: 'Electronics',
    images: [
      'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800',
      'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800',
      'https://images.unsplash.com/photo-1606980707229-7d8f8c86f7aa?w=800',
    ],
    specifications: {
      'Sensor': '24MP APS-C CMOS',
      'Video': '4K @ 30fps',
      'ISO Range': '100-25600',
      'Weight': '450g',
      'Battery Life': '800 shots',
    },
    stock: 25,
    featured: true,
    rating: 4.5,
    reviewCount: 128,
    createdAt: new Date('2024-01-15').toISOString(),
  },
  {
    id: '2',
    name: 'Wireless Headphones',
    slug: 'wireless-headphones',
    description: 'Premium noise-cancelling wireless headphones with 30-hour battery life and exceptional sound quality.',
    price: 299.99,
    brand: 'AudioPro',
    category: 'Electronics',
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800',
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=800',
    ],
    specifications: {
      'Battery Life': '30 hours',
      'Connectivity': 'Bluetooth 5.0',
      'Weight': '250g',
      'Drivers': '40mm',
      'Noise Cancellation': 'Active ANC',
    },
    stock: 50,
    featured: true,
    rating: 4.7,
    reviewCount: 256,
    createdAt: new Date('2024-02-01').toISOString(),
  },
  {
    id: '3',
    name: 'Smart Watch',
    slug: 'smart-watch',
    description: 'Advanced fitness tracking smartwatch with heart rate monitoring, GPS, and water resistance.',
    price: 399.99,
    brand: 'FitTech',
    category: 'Wearables',
    images: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800',
      'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=800',
    ],
    specifications: {
      'Display': '1.4" AMOLED',
      'Battery': '7 days',
      'Water Resistance': '5ATM',
      'GPS': 'Built-in',
      'Sensors': 'Heart rate, SpO2, Accelerometer',
    },
    stock: 35,
    featured: true,
    rating: 4.3,
    reviewCount: 89,
    createdAt: new Date('2024-01-20').toISOString(),
  },
  {
    id: '4',
    name: 'Laptop Stand',
    slug: 'laptop-stand',
    description: 'Ergonomic aluminum laptop stand with adjustable height and cooling design.',
    price: 49.99,
    brand: 'OfficeEase',
    category: 'Accessories',
    images: [
      'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800',
    ],
    specifications: {
      'Material': 'Aluminum Alloy',
      'Adjustable': 'Yes',
      'Compatibility': 'Up to 17 inches',
      'Weight': '800g',
      'Color': 'Space Gray',
    },
    stock: 100,
    featured: false,
    rating: 4.6,
    reviewCount: 45,
    createdAt: new Date('2024-02-10').toISOString(),
  },
  {
    id: '5',
    name: 'Mechanical Keyboard',
    slug: 'mechanical-keyboard',
    description: 'RGB backlit mechanical keyboard with hot-swappable switches and programmable keys.',
    price: 159.99,
    brand: 'KeyMaster',
    category: 'Accessories',
    images: [
      'https://images.unsplash.com/photo-1595225476474-87563907a212?w=800',
      'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800',
    ],
    specifications: {
      'Switch Type': 'Mechanical Blue',
      'Backlight': 'RGB',
      'Layout': '104 keys',
      'Hot-swap': 'Yes',
      'Cable': 'Braided USB-C',
    },
    stock: 60,
    featured: false,
    rating: 4.8,
    reviewCount: 234,
    createdAt: new Date('2024-01-25').toISOString(),
  },
  {
    id: '6',
    name: 'Portable SSD',
    slug: 'portable-ssd',
    description: 'Ultra-fast 1TB portable SSD with USB-C connectivity and hardware encryption.',
    price: 179.99,
    brand: 'DataSpeed',
    category: 'Storage',
    images: [
      'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=800',
    ],
    specifications: {
      'Capacity': '1TB',
      'Interface': 'USB 3.2 Gen 2',
      'Speed': 'Up to 1050MB/s',
      'Encryption': 'Hardware AES-256',
      'Weight': '45g',
    },
    stock: 40,
    featured: false,
    rating: 4.4,
    reviewCount: 67,
    createdAt: new Date('2024-02-05').toISOString(),
  },
  {
    id: '7',
    name: 'Gaming Mouse',
    slug: 'gaming-mouse',
    description: 'High-precision gaming mouse with 16000 DPI sensor and customizable RGB lighting.',
    price: 79.99,
    brand: 'GamePro',
    category: 'Accessories',
    images: [
      'https://images.unsplash.com/photo-1527814050087-3793815479db?w=800',
    ],
    specifications: {
      'DPI': 'Up to 16000',
      'Buttons': '8 programmable',
      'Polling Rate': '1000Hz',
      'Weight': '95g',
      'Cable': 'Braided',
    },
    stock: 75,
    featured: true,
    rating: 4.7,
    reviewCount: 178,
    createdAt: new Date('2024-01-30').toISOString(),
  },
  {
    id: '8',
    name: 'USB-C Hub',
    slug: 'usb-c-hub',
    description: '7-in-1 USB-C hub with HDMI, USB 3.0, SD card reader, and power delivery.',
    price: 59.99,
    brand: 'ConnectHub',
    category: 'Accessories',
    images: [
      'https://images.unsplash.com/photo-1625948515291-69613efd103f?w=800',
    ],
    specifications: {
      'Ports': '7',
      'HDMI': '4K @ 30Hz',
      'USB': '3x USB 3.0',
      'Power Delivery': 'Up to 100W',
      'Material': 'Aluminum',
    },
    stock: 85,
    featured: false,
    rating: 4.5,
    reviewCount: 92,
    createdAt: new Date('2024-02-08').toISOString(),
  },
];

export const mockReviews: Review[] = [
  {
    id: 'r1',
    productId: '1',
    userName: 'John Doe',
    rating: 5,
    title: 'Excellent camera!',
    comment: 'This camera exceeded my expectations. The image quality is outstanding and the 4K video is crystal clear. Highly recommend for anyone serious about photography.',
    createdAt: new Date('2024-02-15').toISOString(),
    verified: true,
  },
  {
    id: 'r2',
    productId: '1',
    userName: 'Sarah Smith',
    rating: 4,
    title: 'Great value for money',
    comment: 'Very good camera for the price. The only downside is that it can be a bit heavy for long shooting sessions.',
    createdAt: new Date('2024-02-10').toISOString(),
    verified: true,
  },
  {
    id: 'r3',
    productId: '2',
    userName: 'Mike Johnson',
    rating: 5,
    title: 'Best headphones I\'ve owned',
    comment: 'The noise cancellation is incredible. Battery life is exactly as advertised. Sound quality is top-notch.',
    createdAt: new Date('2024-02-18').toISOString(),
    verified: true,
  },
  {
    id: 'r4',
    productId: '2',
    userName: 'Emily Chen',
    rating: 5,
    title: 'Perfect for travel',
    comment: 'These headphones are perfect for my daily commute. The ANC blocks out all the noise and they\'re very comfortable.',
    createdAt: new Date('2024-02-12').toISOString(),
    verified: false,
  },
  {
    id: 'r5',
    productId: '3',
    userName: 'David Lee',
    rating: 4,
    title: 'Good fitness tracker',
    comment: 'Tracks all my activities accurately. The battery really does last a week. Would give 5 stars but the app could be better.',
    createdAt: new Date('2024-02-14').toISOString(),
    verified: true,
  },
  {
    id: 'r6',
    productId: '5',
    userName: 'Alex Brown',
    rating: 5,
    title: 'Amazing typing experience',
    comment: 'The mechanical switches feel great and the RGB lighting is gorgeous. Hot-swap feature is a game changer.',
    createdAt: new Date('2024-02-16').toISOString(),
    verified: true,
  },
  {
    id: 'r7',
    productId: '7',
    userName: 'Chris Wilson',
    rating: 5,
    title: 'Perfect for gaming',
    comment: 'Super responsive and comfortable. The customization options are endless. Best gaming mouse I\'ve used.',
    createdAt: new Date('2024-02-17').toISOString(),
    verified: true,
  },
];
